sudo: required
services:
  - docker

before_install:
  - docker build  -t hugotess/react-test -f ./frontend/Dockerfile.dev ./frontend
  - docker build -t hugotess/server -f ./server/Dockerfile.dev ./server

script:
  - docker run hugotess/react-test npm run test -- --coverage
  - docker run hugotess/server npm run test -- --coverage

after_success:
  - docker build -t hugotess/multi-frontend ./frontend # no need to specify dockerfile when it's not a special file name
  - docker build -t hugotess/multi-server ./server
  - docker build -t hugotess/multi-nginx ./nginx
  - docker build -t hugotess/multi-worker ./worker

  # log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push build images to docker hub
  - docker push hugotess/multi-frontend
  - docker push hugotess/multi-server
  - docker push hugotess/multi-nginx
  - docker push hugotess/multi-worker
